### ISSUE TITLE
编辑预览和实际生成页面不一致的问题

### ISSUE THREAD

**Issue by JadeVane** [JaxsonWang/WP-Editor.md#160]
### **用markdown编辑时预览页面是这样的：**
![image](https://user-images.githubusercontent.com/34258753/39955253-35121858-55fe-11e8-95eb-6240654dbebe.png)
### **但实际发布后页面是这样的：**
![image](https://user-images.githubusercontent.com/34258753/39955255-479846fa-55fe-11e8-9c00-f1a2ce9e6948.png)
### **下面是调试信息：**
```
系统环境	Linux
运行环境	nginx/1.13.10
PHP版本	7.1.14
PHP运行环境	fpm-fcgi
Browser Information	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
WordPress版本	4.9.5
插件版本	5.0.7
jQuery版本	1.12.4
当前用户权限	administrator
WordPress地址	https://wenjinyu.me
站点地址	https://wenjinyu.me
常规设置	task_list => on 
imagepaste => on 
live_preview => on 
sync_scrolling => on 
html_decode => off 
static_cdn => //cdn.bootcss.com 
编辑器设置	theme_style => default 
code_style => default 
语法高亮设置	highlight_mode_auto => on 
line_numbers => on 
show_language => on 
highlight_library_style => twilight 
customize_my_style => notiong 
highlight_mode_customize => off 
Emoji表情设置	support_emoji => on 
文章目录设置	support_toc => off 
科学公式设置	support_katex => off 
流程图设置	support_flowchart => off 
时序图设置	support_sequence => off 
sequence_style => simple 
高级设置	0 => 
```

**Comment by JaxsonWang** [comment]
see https://github.com/JaxsonWang/WP-Editor.md/issues/36

**Comment by JadeVane** [comment]
我对CSS不大了解，可以稍微说一下怎么做吗？或者使用哪些关键字可以搜索到答案？

**Comment by JaxsonWang** [comment]
@JadeVane 你可以尝试在自定义-额外css添加下面代码：

```css
.entry-content .code {
    padding: 0;
    padding-top: 0.2em;
    padding-bottom: 0.2em;
    margin: 0;
    font-size: 85%;
    background-color: rgba(27,31,35,0.05);
    border-radius: 3px;
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```

**Comment by JadeVane** [comment]
已经添加进额外css，但是没有作用

**Comment by JaxsonWang** [comment]
呃呃，抱歉写错了是：

```css
.entry-content .code {
    padding: 0;
    padding-top: 0.2em;
    padding-bottom: 0.2em;
    margin: 0;
    font-size: 85%;
    background-color: rgba(27,31,35,0.05);
    border-radius: 3px;
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```

我上面多一个点

**Comment by JadeVane** [comment]
其实和上面的没什么区别。。。。

**Comment by JaxsonWang** [comment]
```css
.entry-content code {
    padding: 0;
    padding-top: 0.2em;
    padding-bottom: 0.2em;
    margin: 0;
    font-size: 85%;
    background-color: rgba(27,31,35,0.05);
    border-radius: 3px;
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```
