### ISSUE TITLE
相当不错的一款插件，md 导入问题

### ISSUE THREAD

**Issue by barretlee** [JaxsonWang/WP-Editor.MD#18]
先赞一个。

目前插件貌似并没有储存 raw md 文件？
不知道是否可以通过什么方式，将 md 文章导入到 wp，并且让导入的内容与这款插件适配。

**Comment by JaxsonWang** [comment]
你可以试试这个：[md-to-wp](https://github.com/jennschiffer/md-to-wp)

**Comment by barretlee** [comment]
我看到数据库中有个字段是 `post_content_filetered`，有些 md editor 会把 raw md 文件内容储存到这个字段中，WP-Editor 是如何处理的呀？

我比较期望数据库能够同时保存 html 和 md 文件，这也方便后期对文章做批量处理。

**Comment by JaxsonWang** [comment]
保存md问做不到，不过我记得有个插件可以把wp文章导出md格式的文件，你可以在wp插件库搜下。

WP-Editor.md原理和你说的一样，`post_content_filetered`字段存储md文章数据，经过插件渲染发布html文件。

**Comment by barretlee** [comment]
我找了两个小时，试用了七八款 MD Editor，确实没找到特别满意的，就你这款，挺不错。

报一个 bug 吧：当 Jetpack 开启 MD 后，由于你 Copy 了 Jetpack 的代码，其中有一个 Class WPCom_Markdown 会被定义两次，报错。

你可以在定义 Class 之前先判断是否已经定义 `class_exists`。

**Comment by JaxsonWang** [comment]
好的，明天解决！谢谢！

**Comment by barretlee** [comment]
另外，还有一个功能增强，我帮你补上：

```css

@media screen and (max-width: 1200px) {
  .editormd .CodeMirror {
    width: 100% !important;
    margin-top: 40px !important;
  }
  .editormd-toolbar {
    height: 40px;
    overflow: hidden;
    overflow-x: auto;
    white-space: nowrap;
  }
  .editormd-toolbar::-webkit-scrollbar, .editormd ::-webkit-scrollbar-thumb {
    width: 0px;
    background: transparent;
  }
}
.wp-editor-expand #wp-content-editor-container {
  max-width: 100%;
}
```

能够适配移动端。
