### ISSUE TITLE
Mermaid 流程图如何居中显示？

### ISSUE THREAD

**Issue by Skywt2003** [JaxsonWang/WP-Editor.md#200]
默认画的 Mermaid 流程图是靠左的，如果直接加 center ，mermaid 图会显示不出来（只显示代码）。Mermaid 插件好像本身也没有提供居中的选项。如何居中显示呢？

**Comment by JaxsonWang** [comment]
查看mermaid没发现什么居中的方法。

可以的话直接在你的主题样式添加css：
```css
.mermaid {
        text-align: center;
}
```

同样也可以达到居中效果
