### ISSUE TITLE
\tag{1} 在Live preview显示正确，但在最终页面显示到页面范围外

### ISSUE THREAD

**Issue by vanish87** [JaxsonWang/WP-Editor.md#276]
\tag{1} 在Live preview显示正确，但在最终页面显示到页面范围外
$$\vec{N\prime}\cdot\vec{T\prime} = 0 \tag{1}$$
换用Wp HyperMD正常，但是需要四个\来换行

**Comment by JaxsonWang** [comment]
理论上这归属于主题问题，例如``主题可以在文章的class添加:

```css
.entry-content {
    position: relative;
}
```

解决这个问题。

至于换行计划下个版本和wp-hypermd同步。
