### ISSUE TITLE
使用引用在前端无样式等

### ISSUE THREAD

**Issue by skyfore** [JaxsonWang/WP-Editor.MD#30]
比如我的markdown 为

```markdown
> 这是一个引用
```

但是在前端上表现出的是有 `<blockquote>` 包裹的语句，但是样式上无任何变化，请问这个是我自己设置上的问题吗？而且使用 
```markdown
`23333`
```
这种也没有语法的任何高亮

在设置里面我勾选了
 1. 前端支持语法高亮
 2. Prism语法高亮加载库

使用 table 的时候也会无样式的情况

实际的页面和写的时候的预览页面表现不一致。
请问这种该如何解决？谢谢 :smiley:

**Comment by JaxsonWang** [comment]
只要是源代码正确解析就可以了。

像你这样的情况可能是主题作者没有添加相关的样式，联系作者添加样式吧

**Comment by skyfore** [comment]
@JaxsonWang 请问需要添加什么样式呢？比如需要加什么前缀，因为假如我直接添加 
```css
blockquote {
  /* 
     do something
  */
}
```
这样会污染全局的样式表的。

**Comment by JaxsonWang** [comment]
这个我是在官方默认主题找的样式：

```css
blockquote {
    border-left: 4px solid #707070;
    border-left: 4px solid rgba(51, 51, 51, 0.7);
    color: #707070;
    color: rgba(51, 51, 51, 0.7);
    font-size: 18px;
    font-size: 1.8rem;
    font-style: italic;
    line-height: 1.6667;
    margin-bottom: 1.6667em;
    padding-left: 0.7778em;
}
```

至于你说的污染全局渲染样式表，不会的，都没有这个怎么会污染？

而且插件不会接管样式渲染
