### ISSUE TITLE
关于Katex公式的字体大小如何调整

### ISSUE THREAD

**Issue by schrodingercatss** [JaxsonWang/WP-Editor.md#319]
在使用markdown书写Katex公式时，渲染的字体过大，影响阅读感受，如何修改默认渲染的字体大小呢？

**Comment by JaxsonWang** [comment]
自定义css添加：

```css
.katex {
    font-size: 16px;
}
```
