### ISSUE TITLE
行内代码,在文章浏览时没有效果

### ISSUE THREAD

**Issue by netAir** [JaxsonWang/WP-Editor.MD#36]
行内代码,在文章浏览时没有效果

**Comment by JaxsonWang** [comment]
编辑写的文章贴上来

**Comment by netAir** [comment]
https://netair.xyz/%E6%80%BB%E7%BB%93%E8%B7%A8%E5%9F%9Fhttp%E8%AF%B7%E6%B1%82/
这是文章链接,和markdown内容
### 例如
* `www.a.com`页面中的`<img>`标签中`src=//www.b.com/a.jpg`
* `a.netair.xyz`向`b.netair.xyz`提交表单
* `netair.xyz `的js脚本向`netair.xyz:8080`get请求资源
* 等等

**Comment by JaxsonWang** [comment]
从页面解析来看，源代码是正确解析了。

```html
<ul>
<li><code>www.a.com</code>页面中的<code>&lt;img&gt;</code>标签中<code>src=//www.b.com/a.jpg</code></li>
<li><code>a.netair.xyz</code>向<code>b.netair.xyz</code>提交表单</li>
<li><code>netair.xyz</code>的js脚本向<code>netair.xyz:8080</code>get请求资源</li>
<li>等等</li>
</ul>
```

是你主题的作者没有加入行内代码展示的样式表。

我随便写个，你加入样式表看看：
```css
.entry-content .code {
    padding: 0;
    padding-top: 0.2em;
    padding-bottom: 0.2em;
    margin: 0;
    font-size: 85%;
    background-color: rgba(27,31,35,0.05);
    border-radius: 3px;
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```
